[package]
name = "gtnh-flow-chart"
version = "18.7.38"
description = "GTNH Flow Chart desktop app"
authors = ["GTNH Flow Chart"]
edition = "2021"

[lib]
name = "gtnh_flow_chart_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
